Use newer flake8 to run on ubuntu-focal Zuul machines
flake8 2.5.5 fails on ubuntu-focal zuul machines running python3.8
with the following error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

The update removes the hacking constraint to use newer flake8. This
also ignores new warnings/errors, which should be addressed in a
future update to remove the ignores.

Change-Id: Ib24639adeea4da3063fb403a8e8484937f9e1a9f
Partial-Bug: 1895054
Signed-off-by: Don Penney <don.penney@windriver.com>